export const USER_CONSTANTS = {
    LOGIN_USER: 'LOGIN_USER',
    LOGIN_USER_BEGIN: 'LOGIN_USER_BEGIN',
    LOGIN_USER_SUCCESS: 'LOGIN_USER_SUCCESS',
    LOGIN_USER_FAILURE: 'LOGIN_USER_FAILURE',

    SET_ACCESS_TOKEN: 'SET_ACCESS_TOKEN',

    LOGOUT_USER: 'LOGOUT_USER',
    LOGOUT_USER_BEGIN: 'LOGOUT_USER_BEGIN',
    LOGOUT_USER_SUCCESS: 'LOGOUT_USER_SUCCESS',
    LOGOUT_USER_FAILURE: 'LOGOUT_USER_FAILURE',

    CLOSE_ERROR: 'CLOSE_ERROR',
}
