export const USER_CONSTANTS = {
    LOGIN_USER: 'LOGIN_USER',
    LOGIN_USER_BEGIN: 'LOGIN_USER_BEGIN',
    LOGIN_USER_SUCCESS: 'LOGIN_USER_SUCCESS',
    LOGIN_USER_FAILURE: 'LOGIN_USER_FAILURE',

    REFRESH_USER: 'REFRESH_USER',
    REFRESH_USER_BEGIN: 'REFRESH_USER_BEGIN',
    REFRESH_USER_SUCCESS: 'REFRESH_USER_SUCCESS',
    REFRESH_USER_FAILURE: 'REFRESH_USER_FAILURE',

    LOGOUT_USER: 'LOGOUT_USER',
    LOGOUT_USER_BEGIN: 'LOGOUT_USER_BEGIN',
    LOGOUT_USER_SUCCESS: 'LOGOUT_USER_SUCCESS',
    LOGOUT_USER_FAILURE: 'LOGOUT_USER_FAILURE',
}
